#Create Custom Container Image, and Push it to DockerHub Registry
---
- hosts: localhost
  tasks: 
  - name: Pull .war artifact from Artifactory
    become: true
    get_url:
      url: http://3.227.46.127:8082/artifactory/project-a-libs-release-local/com/Stanleyobazee/Stanleyobazee/1.0/Stanleyobazee-1.0.war
      dest: /home/ubuntu
      url_username: admin
      url_password: Infinity007!

  - name: Rename .war Artifact
    command: mv -f Stanleyobazee-1.0.war webapp.war
  
  - name: make sure python docker library is there for the docker_image module execution
    ansible.builtin.pip:
      name: docker
      
  - name: install docker engine
    apt:
      pkg:
      - docker
      - docker.io
    become: yes

  - name: Pull Tomcat  Container Image
    docker_image:
      name: !unsafe tomcat:latest
      source: pull
      force_tag: yes

  - name: Build image and with build args
    docker_image:
      name: efeben007/efe-repo
      repository: efeben007/efe-repo:{{build_number}}
      build:
        path: /home/ubuntu
        args:
          listen_port: 8080
      source: build
      force_source: yes
  
  
  - name: Log into DockerHub
    docker_login:
     username: efeben007
     password: Infinity007!
 

  - name: Push to docker hub
    docker_image:
        name: efeben007/efe-repo
        repository: efeben007/efe-repo:{{build_number}}
        force_tag: yes
        push: yes
        source: local
    






